language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: MObM1K+TJvkmWRRlkbQT45UJr02pUCd3AAXEc1H7/oBSfexoN0hQDvUFcOL1nYLheRP7cKvHU94sc4tnjw01QLEJJ3keR+zKOq9mf/Zw93JKQcYQHd6SjpWaGj9D2icE2fhrCL6VUmtZEcg/b7DUitlYq9uqJYKTXcBeD4ESO/e6i66WE/GsnksDGaLX4e1b/8oSY1yCQ+1LxWvIDvqw+HwRU4T1oeiMVfbSACjFqzr5uDr0BynS2GZwV7fLHBsaQNbWUEgaIbTyqbn2TcvM6y0BORicEADXL9e8dKojx+XyAs0tFSRCgWqTJiYP7Fi+KEabyxbZvh9C4+MdzTPzpuBxBSHtZ0/yBLIJb0BNlN9vj3Rj7HsFm6NcmfYkx2igcAXgUQ3x7ONe6OHtucF275gTm5MfRv2YcSlzqFRUj76s5F8nMRFi3jrpVVGri8haO85/+voCPWlJIMiaUilSRvq6P4Y5Mx2OKVAwri2zOUwXcjq/eG8tYD12v6HvWZD4GXO/7/0bb4HHpA82uFUXOSXkhS85AwuEloDCf8XEQ4sWzyYlt0E7xEj9m3hGMdNNjgyafjcZvseyruUhWS7ql80a78ItjUpve+u5pQjAQWesDIAzvib2DB3hElyWup/ObUeHeOZppi9eQwHOM2Cokm5MhJD34WnIO2trbAunx2M=
    # FIREBASE_SECRET
    - secure: H3h2nqr2aM0CT2I2CgvGljneEs07bGUApsUQ12jxQi00/CNvhAYhhAC0yNt/LMXSXiI9DzH9S8nMmr5DO78apQ8Viw30yH2R3bpep+EBx/Ao1RbYqJjzr0krX0aq4zZCwI2S6vr/Ma92+FknCoYomwCkDXVHzMShNJZY5ofxlD4gc+WkZS5tv4ADyr9JJKTck4fQ6fCPjEFWOfVKYQYhfngVq6Nv7+2/deIEONxMBmhln46WQaYI/oEF2qcUjPOp2OGXils1tD5y295jXX/Y0wxLHJa31NVPcYhDx4e1PkGgkxFDedJvWlHJOUYi/B4nRRTCcGq+35EPZ/ruQXsbZWF+eJ2piChpW2J0evNGyuo1tA0r/aswKXmfUNojSlEnNKKkRQIFKZjbCpSQPHdwvfR8t8c9KPttTPdXN8EgKDzhBKsNzHw9bohHfpBuUV+VWctlBYVsriMq68iDV2Ui/TJZhBe7zAXxroC54qzRTTg6/9ReWinNhosZ60fRRAIDErr7aHLhyIyVV3OtSxFbxbpn6Zy94ta4T/wSlcCqACZKETJbXsFzG7NBnHD3jdmdq3MtDqw8RmPfEY186h+Qx6V8zE59NTZWDMGVTWTA1AapQzSSKRWJtuvLwAGXZuQEC5mboC7RvBb6zTGODWfBUfoAvLOO3eOHJgHeTCLZszs=
